# Generated by Django 5.1.3 on 2025-08-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
